{"uuid": "af0a7e19-7b23-46b9-8a9e-5db4632adf95", "children": ["2c8a813c-325b-46ba-8142-a7f5a5326d25", "29593486-f69e-4b1d-8116-9fcb9d10bd3e", "45fcb8ac-f3b2-4656-a2e4-b1616babf05d"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1039d1f30>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/src/conftest.py\", line 22, in driver\n    driver_instance = webdriver.Remote('http://localhost:4723', options=options)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 229, in __init__\n    super().__init__(\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 319, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 306, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 326, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/_request_methods.py\", line 143, in request\n    return self.request_encode_body(\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/_request_methods.py\", line 278, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n"}, "start": 1730444457431, "stop": 1730444457511}], "start": 1730444457431, "stop": 1730444459076}