{"uuid": "51cd1f23-7cf0-4fd1-8c32-e32746b1b295", "children": ["ace260ae-b6ae-4236-8220-f0d46320e388", "3966e094-c2d5-4946-8a71-b7245f4404cc", "87fe16ba-f94a-483c-a85e-10602182324f", "ca2a0128-95b5-40fb-ab74-2bfba99e51a8", "c66e444f-5951-4544-9b99-70edfb2676b5"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110161f00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/src/conftest.py\", line 22, in driver\n    driver = webdriver.Remote('http://localhost:4723', options=options)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 229, in __init__\n    super().__init__(\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 319, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 306, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 326, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/_request_methods.py\", line 143, in request\n    return self.request_encode_body(\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/_request_methods.py\", line 278, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n"}, "start": 1727164629131, "stop": 1727164629167}], "start": 1727164629131, "stop": 1727164631091}