{"uid":"dada68726e1c89e0","name":"test_login_success","fullName":"src.tests.test_login#test_login_success","historyId":"d7250828c2bc668cfe9858cb88b836ce","time":{"start":1727253775909,"stop":1727253790838,"duration":14929},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"driver","time":{"start":1727253760439,"stop":1727253775904,"duration":15465},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"driver::0","time":{"start":1727253830991,"stop":1727253835964,"duration":4973},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/kevin/Library/Android/sdk/platform-tools/adb -P 5037 -s 1902390100180748 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 1'; Command output: adb: device offline\n\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/kevin/Library/Android/sdk/platform-tools/adb -P 5037 -s 1902390100180748 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 1'; Command output: adb: device offline\n\n    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)\n    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)\n","statusTrace":"  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/src/conftest.py\", line 26, in driver\n    driver.quit()\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 476, in quit\n    self.execute(Command.QUIT)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/venv/lib/python3.10/site-packages/appium/webdriver/errorhandler.py\", line 125, in check_response\n    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"labels":[{"name":"tag","value":"run(order=1)"},{"name":"tag","value":"@pytest.mark.usefixtures('driver')"},{"name":"parentSuite","value":"src.tests"},{"name":"suite","value":"test_login"},{"name":"host","value":"macbooks-MacBook-Air.local"},{"name":"thread","value":"34773-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"src.tests.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":["run(order=1)","@pytest.mark.usefixtures('driver')"]},"source":"dada68726e1c89e0.json","parameterValues":[]}